### ISSUE TITLE
conv2d_backward on Wgpu backend is too slow

### ISSUE THREAD

**Issue by AsherJingkongChen** [tracel-ai/burn#2260]
**Describe the bug**

I used the public API `burn::nn::Conv2d<Autodiff<Wgpu>>`, which internally calls `conv::conv2d_backward<Wgpu>` in `burn_tensor`. The program gets stucked there when my input tensor size increases.

- Input shape: `[1, 3, 10, 10]`, Speed: Acceptable
- Input shape: `[1, 3, 18, 18]`, Speed: ~900ms
- Input shape: `[1, 3, 30, 30]`, Speed: ~3100ms (The 3rd run)

**To Reproduce**

I executed the code on Apple Silicon (Metal v3.1).

I have written the minimal reproducible example here, please run the command `RUST_LOG=debug cargo r -r -p conv2d-autodiff`. You can adjust the input shape to test:

> *Cargo.toml*

```toml
[package]
edition = "2021"
name = "conv2d-autodiff"
version = "0.0.0"

[dependencies]
anyhow = {version = "1.0.86", default-features = false, features = ["std"]}
log = {version = "0.4.22", default-features = false}
pretty_env_logger = {version = "0.5.0", default-features = false}

[dependencies.burn]
git = "https://github.com/tracel-ai/burn.git"
rev = "a9f941d403686abdb5ff2f3bea80219ecd6228a9"
default-features = false
features = ["autodiff", "default", "template", "wgpu"]
```

> *src/main.rs*

```rust
use burn::{
    backend::{Autodiff, wgpu},
    nn::{conv::Conv2dConfig, PaddingConfig2d},
    tensor::{Distribution, Tensor},
};

fn main() -> anyhow::Result<()> {
    pretty_env_logger::formatted_timed_builder()
        .parse_default_env()
        .try_init()?;

    // Parameters
    type B = Autodiff<wgpu::JitBackend<wgpu::WgpuRuntime, f32, i32>>;
    let device = &Default::default();

    // Input (requires gradient)
    let x =
        Tensor::<B, 4>::random([1, 3, 18, 18], Distribution::Default, device)
            .require_grad();

    // 2D Convolution model
    let model = Conv2dConfig::new([3, 3], [2, 2])
        .with_bias(false)
        .with_groups(3)
        .with_padding(PaddingConfig2d::Same)
        .init(device);

    // Forward pass
    let y = model.forward(x.to_owned());

    // Backward pass
    log::warn!(target: "event", "Backward pass");
    let grads = &mut y.backward();

    // Retrieve gradients
    let x_grad = x.grad_remove(grads);
    let w_grad = model.weight.grad_remove(grads);

    assert!(x_grad.is_some());
    assert!(w_grad.is_some());

    Ok(())
}
```

**Expected behavior**

The generated shader code by `naga` is too large, and the program gets stucked when calling `conv2d_backward`. It should be faster. The speed will be a problem when training CNN models.

**Logs**

My log file had 89488 lines, and I extracted some parts from it to explain what is happening:

> 36000+ naga resolving events before finishing translation to Metal (Note: input tensor shape is `[1, 3, 18, 18]`)

```log
 2024-09-09T09:41:05.857Z DEBUG naga::front                          > Resolving [36451] = Access { base: [36450], index: [18] } : Value(Pointer { base: [0], space: Storage { access: StorageAccess(LOAD | STORE) } })
 2024-09-09T09:41:05.857Z DEBUG naga::front                          > Resolving [36452] = Load { pointer: [33] } : Handle([0])
 2024-09-09T09:41:05.857Z DEBUG naga::front                          > Resolving [36453] = As { expr: [36452], kind: Float, convert: Some(4) } : Value(Scalar(Scalar { kind: Float, width: 4 }))
```

**Desktop**
 - OS: macOS
 - Version: 14.6.1

**Additional context**

I may find the bug later or re-implement my own backward kernel. It is required for my project.
