### ISSUE TITLE
Scalars have caused some issues with onnx import

### ISSUE THREAD

**Issue by loloxwg** [tracel-ai/burn#2699]
**Describe the bug**
Scalars have caused some issues with onnx import..in this case it looks like the constant node import does not correctly handle them. 

**To Reproduce**

1. Go to https://huggingface.co/AndrewOgn/resnet_onnx/tree/main down the onnx file
2. Run code 
```fn main() {
    // Generate the model code from the ONNX file.

    // If not embedded-model, then model is loaded from the file system (default).
    ModelGen::new()
        .input("src/model/resnet_model.onnx")
        .out_dir("model/")
        .development(true)
        .run_from_script();
    
}
```

**Expected behavior**

Generage a model.rs file

**Screenshots**

![image](https://github.com/user-attachments/assets/c05102df-cdfa-433e-9277-2ca1bd80fe4a)

**Desktop (please complete the following information):**
 - OS: Mac OS m1
 - Browser Chrome
 - Version da8de562b0f67869c8a8c629b8535f938fd317f9

**Smartphone (please complete the following information):**

**Additional context**

**Comment by polarathene** [comment]
Just providing a status update 6 months later this is still the same failure:

```rust
  DEBUG burn_import::burn::graph: Registering node => 'concat'
  ERROR burn_import::logger: PANIC => panicked at /root/.cargo/git/checkouts/burn-6c277d792b0d5d7a/1f5ccd4/crates/burn-import/src/burn/ty.rs:194:9:
  assertion `left != right` failed: Trying to create TensorType with dim = 0 - should be a Scalar instead!
    left: 0
   right: 0
```

Relevant issue refs:
- https://github.com/tracel-ai/burn/issues/2781#issuecomment-2665684906
- https://github.com/tracel-ai/burn/issues/1689#issuecomment-2399691184

## Reproduction

Quick and easy reference for a copy/paste reproduction via either a Docker Compose `compose.yaml` or `Dockerfile`, both have source files embedded all into a single file.

## Docker Compose (`compose.yaml`)

```bash
# NOTE: To build an image variant with a different model, prefix the command with `ONNX_MODEL_URL=url-here`:
docker compose run --rm -it burn-onnx cargo build
```

**`compose.yaml`:**

<details>
<summary>Click to view</summary>

```yaml
name: onnx-example

volumes:
  cargo-home:
  cargo-target:

services:
  burn-onnx:
    image: localhost/burn-onnx
    # Necessary source files embedded into the Compose config for convenience:
    configs:
      - source: cargo-toml
        target: /example/Cargo.toml
      - source: build-rs
        target: /example/build.rs
      - source: lib-rs
        target: /example/src/lib.rs
      - source: module-onnx-model
        target: /example/src/model/mod.rs
    # Persistent volumes for caching runs:
    volumes:
      - cargo-home:/root/.cargo
      - cargo-target:/example/target
    # Build custom image (fetches ONNX model + upgrades opset if required),
    # NOTE: Adjust `ONNX_MODEL_URL` ARG for required model (supports override by using an ENV of the same name)
    pull_policy: build
    build:
      args:
        ONNX_MODEL_URL: ${ONNX_MODEL_URL:-https://huggingface.co/AndrewOgn/resnet_onnx/resolve/main/model.onnx}
      # NOTE: To avoid using the Docker Compose ENV interpolation feature, `$` must be escaped as `$$`:
      dockerfile_inline: |
        FROM fedora:42
        # Install Rust (current stable release) + Python and UV (for opset upgrade script):
        RUN <<HEREDOC
          dnf --setopt=install_weak_deps=0 install -yq rustup gcc python uv && dnf clean all
          rustup-init -y --profile minimal --default-toolchain 1.87
        HEREDOC
        ENV PATH=/root/.cargo/bin:${PATH}
        WORKDIR /example

        # Optional - ONNX opset upgrade script (only needed for older models):
        # Next tag after `v0.17.1` could be used to pin, until then only a commit or branch ref works:
        ARG REF=main
        ARG ONNX_UPGRADE_URL=https://github.com/tracel-ai/burn/raw/$${REF}/crates/burn-import/onnx_opset_upgrade.py
        ADD --chmod=0755 $${ONNX_UPGRADE_URL} onnx-opset-upgrade.py

        # Grab the ONNX model:
        ARG ONNX_MODEL_URL
        ADD $${ONNX_MODEL_URL?model-url-required} src/model/example.onnx
        # Optional (Upgrade opset) - Automate the input prompts for ONNX file read/write paths via printf:
        RUN printf '%s\n' 'src/model/example.onnx' 'src/model/example.onnx' | ./onnx-opset-upgrade.py

configs:
  cargo-toml:
    content: |
      [package]
      name = "onnx-import-example"
      version = "0.1.0"
      edition = "2024"

      [dependencies]

      [build-dependencies]
      #burn-import = "0.17.1"
      burn-import = { git = "https://github.com/tracel-ai/burn.git" }

  build-rs:
    content: |
      use burn_import::onnx::ModelGen;

      fn main() {
        ModelGen::new()
          .input("src/model/example.onnx")
          .out_dir("model/")
          .run_from_script();
      }

  lib-rs:
    content: |
      pub mod model;
      pub use model::example;

  module-onnx-model:
    content: |
      pub mod example {
        include!(concat!(env!("OUT_DIR"), "/model/example.rs"));
      }
```

</details>

---

## Docker CLI (`Dockerfile`)

```bash
# NOTE: To build an image variant with different model, add `--build-arg ONNX_MODEL_URL=url-here`:
docker build --tag localhost/onnx .

# Attempt a build (with optional volumes to cache crate fetching + build target output):
docker run --rm -it -v cargo-home:/root/.cargo/ -v cargo-target:/example/target localhost/onnx cargo build
```

**`Dockerfile`:**

<details>
<summary>Click to view</summary>

```Dockerfile
FROM fedora:42
# Install Rust (current stable release) + Python and UV (for opset upgrade script):
RUN <<HEREDOC
  dnf --setopt=install_weak_deps=0 install -yq rustup gcc python uv && dnf clean all
  rustup-init -y --profile minimal --default-toolchain 1.87
HEREDOC
ENV PATH=/root/.cargo/bin:${PATH}
WORKDIR /example

# Optional - ONNX opset upgrade script (only needed for older models):
# Next tag after `v0.17.1` could be used to pin, until then only a commit or branch ref works:
ARG REF=977e7126e519691cebf8d3111ea653f52c01cbe4
ARG ONNX_UPGRADE_URL=https://github.com/tracel-ai/burn/raw/${REF}/crates/burn-import/onnx_opset_upgrade.py
ADD --chmod=0755 ${ONNX_UPGRADE_URL} onnx-opset-upgrade.py

# Grab the ONNX model:
ARG ONNX_MODEL_URL=https://huggingface.co/AndrewOgn/resnet_onnx/resolve/main/model.onnx
ADD ${ONNX_MODEL_URL?model-url-required} src/model/example.onnx
# Optional (Upgrade opset) - Automate the input prompts for ONNX file read/write paths via printf:
RUN printf '%s\n' 'src/model/example.onnx' 'src/model/example.onnx' | ./onnx-opset-upgrade.py


# Add sources (embedded inline):
# Simplifies reproduction setup via bundling into the same file vs `COPY . /example`

COPY <<HEREDOC Cargo.toml
[package]
name = "onnx-import-example"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
#burn-import = "0.17.1"
burn-import = { git = "https://github.com/tracel-ai/burn.git" }
HEREDOC

COPY <<HEREDOC build.rs
use burn_import::onnx::ModelGen;

fn main() {
  ModelGen::new()
    .input("src/model/example.onnx")
    .out_dir("model/")
    .run_from_script();
}
HEREDOC

COPY <<HEREDOC src/lib.rs
pub mod model;
pub use model::example;
HEREDOC

COPY <<HEREDOC src/model/mod.rs
pub mod example {
  include!(concat!(env!("OUT_DIR"), "/model/example.rs"));
}
HEREDOC
```

</details>
