### ISSUE TITLE
Memory Leak with nn::Linear and Autodiff  (multiple Backends)

### ISSUE THREAD

**Issue by FilePhil** [tracel-ai/burn#2743]
**Describe the bug**
When I use Autodiff  together with Linear Layers, I see a huge memory usage.
I want to create a simple DQN agent, but the amount of steps, result in a quick end because of the leak.

I tested the Backends: Wgpu, Ndarray & Candle. In all cases the device memory raised very quickly.
Also tested with the Burn version 0.15, 0.16 and the current git master.
Without the Autodiff, the memory usage is constant.

**To Reproduce**
Cargo.toml
```toml
  [package]
  name = "burn_test"
  version = "0.1.0"
  edition = "2021"
  
  [dependencies]
  burn = { git =  "https://github.com/tracel-ai/burn.git", features = ["autodiff","ndarray","candle","wgpu"] }
  
  # Enable a small amount of optimization in the dev profile.
  [profile.dev]
  opt-level = 1
  
  # Enable a large amount of optimization in the dev profile for dependencies.
  [profile.dev.package."*"]
  opt-level = 3
```
main.rs
(Layer Sizes are artificially big to show the Issue more clearly)
```rust 
use burn::nn::{Linear, LinearConfig};

use burn::tensor::backend::Backend;
use burn::tensor::Tensor;

use burn::backend::{Autodiff,Wgpu,Ndarray,Candle};


const INPUT_SIZE:usize = 4;
const HIDDEN_SIZE:usize = 8096;
const OUTPUT_SIZE:usize = 4;

fn main() {

    type MyBackend = Wgpu;
    type MyAutodiff = Wgpu;//Autodiff<MyBackend>;
  
    let floats = [[1.0;INPUT_SIZE];32];
    let input = Tensor::<MyAutodiff, 2>::from_floats(floats, &Default::default());

    let linear_0: burn::nn::Linear<MyAutodiff> =  LinearConfig::new(INPUT_SIZE, HIDDEN_SIZE).init(&Default::default());
    let linear_1: burn::nn::Linear<MyAutodiff> =  LinearConfig::new(HIDDEN_SIZE, HIDDEN_SIZE).init(&Default::default());
    let linear_2: burn::nn::Linear<MyAutodiff> =  LinearConfig::new(HIDDEN_SIZE, OUTPUT_SIZE).init(&Default::default());
    
    let mut result = input;
    println!("Start");
    for n in 1..5000{
        result = linear_0.forward(result);
        result = linear_1.forward(result);
        result = linear_2.forward(result);
    }
    println!("End");
}
```

**Expected behavior**
No memory Leak.

**Screenshots**
Video of the Issue:
https://github.com/user-attachments/assets/f9f39312-ecec-4548-9b9f-ded7e4147c16

**Desktop (please complete the following information):**
- **Hardware Model:**                              ASUS PRIME B650M-A WIFI
- **Memory:**                                      32.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 9700X × 16
- **Graphics:**                                    AMD Radeon™ RX 7800 XT
- **Disk Capacity:**                               2.0 TB

- **Firmware Version:**                            3067
- **OS Name:**                                     Fedora Linux 41 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.12.9-200.fc41.x86_64
