### ISSUE TITLE
Install of burn-import from crates.io is broken

### ISSUE THREAD

**Issue by mush42** [tracel-ai/burn#3224]
```
    Updating crates.io index
      Adding burn-import v0.17.0 to dependencies
             Features:
             + burn-ndarray
             + candle-core
             + onnx
             + pytorch
             + thiserror
             + zip
    Updating crates.io index
error: failed to select a version for the requirement `zip = "^2.6.1"`
  version 2.6.1 is yanked
location searched: crates.io index
required by package `burn-import v0.17.0`
    ... which satisfies dependency `burn-import = "^0.17.0"` of package `brnnx v0.1.0 (D:\projects\brnnx)`
```

**Comment by RustyBamboo** [comment]
Also ran into this. Seems that MR #3199 fixed this for the main branch. If using crates.io, can get around this by pulling zip2 2.6.1 from github.
```toml
[patch.crates-io]
# TODO: remove this once crates.io burn-import is updated with the new (non-yanked) zip 3.0.0/4.0.0 version
zip = { git = "https://github.com/zip-rs/zip2", rev="1d42731efcad72e9f653a5ca46ed8306f4a3ca72" }

```
