### ISSUE TITLE
”autotune“ Log specified location or deletion

### ISSUE THREAD

**Issue by chenqi13814529300** [tracel-ai/burn#3326]
Hello, great developer.
When I run the program, I always generate some logs in the execution directory, such as target \ autotune \ 0.6.0Device-4-0-wgpu-wgsl2. I hope to customize this path or not generate these logs.

![Image](https://github.com/user-attachments/assets/f36d4a9c-69b5-43d2-8bb8-d2ecc0744a3c)

**Comment by laggui** [comment]
This points to the autotune cache for cubecl backends (in this case, wgpu).

By default, it will be in the target dir but you can configure it by adding a `cubecl.toml` file to your project.

```toml
[profiling]
logger = { file = "profiling.log", level = "disabled" }

[autotune]
logger = { file = "autotune.log", level = "disabled" }
cache = "target"

[compilation]
logger = { file = "compilation.log", level = "disabled" }
cache = "target"
```

Under `[autotune]` the `cache` field can be one of `"local"`, `"target"` (default),  `"global"` (points to `$HOME/.config`) or a specific path `cache = { file = "/path/to/autotune/cache" }`.
